import React from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { APPS, LOGS } from '../data';
import { AppIcon, Background, BrandHeader, Card, Chevron, SquareIcon, Toggle } from '../components/UI';
import { BottomNav } from '../components/BottomNav';
import { C } from '../theme';

export default function HomeScreen({master,onMaster,onTab,onPermissions,onRecords}:{master:boolean;onMaster:()=>void;onTab:(t:'home'|'apps'|'settings')=>void;onPermissions:()=>void;onRecords:()=>void}){
 const recent=LOGS.slice(0,3);
 return <Background><View style={s.root}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={s.scroll}><BrandHeader/>
  <Card style={s.status}><LinearGradient colors={['#16A9F0','#11D3C0']} style={s.orb}><Text style={s.check}>✓</Text></LinearGradient><View style={{flex:1}}><Text style={s.statusTitle}>{master?'净屏已开启':'净屏已暂停'}</Text><Text style={s.statusSub}>自动跳过 + 网络过滤</Text></View><Toggle value={master} onChange={onMaster}/></Card>
  <View style={s.stats}><Pressable style={{flex:1}} onPress={onRecords}><Card style={s.stat}><SquareIcon symbol="≫" tone="blue" size={62}/><View><Text style={s.statLabel}>今日自动跳过</Text><View style={s.numRow}><Text style={s.num}>28</Text><Text style={s.unit}>次</Text></View></View></Card></Pressable><Pressable style={{flex:1}} onPress={onRecords}><Card style={s.stat}><SquareIcon symbol="◎" tone="green" size={62}/><View><Text style={s.statLabel}>今日网络过滤</Text><View style={s.numRow}><Text style={s.num}>136</Text><Text style={s.unit}>次</Text></View></View></Card></Pressable></View>
  <Card style={s.block}><View style={s.blockHead}><Text style={s.blockTitle}>◷  权限与服务状态</Text><Pressable onPress={onPermissions}><Chevron/></Pressable></View>
   {[['≫','blue','自动跳过权限','帮助自动跳过应用开屏广告','已开启'],['◆','green','网络过滤状态','拦截广告请求，净化网络','运行中'],['▣','purple','后台运行','保持服务持续工作','已允许']].map((r:any,i)=><Pressable key={i} onPress={onPermissions} style={s.row}><SquareIcon symbol={r[0]} tone={r[1]} size={52}/><View style={{flex:1}}><Text style={s.rowTitle}>{r[2]}</Text><Text style={s.rowSub}>{r[3]}</Text></View><Text style={s.goodPill}>{r[4]}</Text><Chevron/></Pressable>)}
  </Card>
  <Card style={s.block}><View style={s.blockHead}><Text style={s.blockTitle}>◷  最近记录</Text><Pressable onPress={onRecords}><Text style={s.link}>查看全部  ›</Text></Pressable></View>{recent.map((l,i)=>{const a=APPS.find(x=>x.id===l.appId)!;return <View key={i} style={s.logRow}><Text style={s.time}>{l.time}</Text><AppIcon source={a.icon} size={42}/><Text style={s.logName}>{a.name}</Text><Text style={[s.logAction,l.type==='fail'&&{color:C.red}]}>●  {l.text}</Text></View>})}</Card>
  <Pressable onPress={onRecords}><View style={s.notice}><Text style={s.noticeIcon}>💡</Text><Text style={s.noticeText}>已为你减少广告打扰</Text><Chevron/></View></Pressable>
 </ScrollView><BottomNav active="home" onChange={onTab}/></View></Background>
}
const s=StyleSheet.create({root:{flex:1},scroll:{padding:18,paddingBottom:112},status:{padding:20,flexDirection:'row',alignItems:'center',gap:16,marginBottom:14},orb:{width:94,height:94,borderRadius:47,alignItems:'center',justifyContent:'center'},check:{fontSize:55,color:'#fff',fontWeight:'900'},statusTitle:{fontSize:30,fontWeight:'900',color:C.navy},statusSub:{fontSize:17,fontWeight:'800',color:'#47658B',marginTop:4},stats:{flexDirection:'row',gap:12,marginBottom:14},stat:{padding:15,flexDirection:'row',alignItems:'center',gap:12,minHeight:112},statLabel:{fontSize:15,fontWeight:'900',color:C.text},numRow:{flexDirection:'row',alignItems:'baseline'},num:{fontSize:38,fontWeight:'900',color:C.navy},unit:{fontSize:17,fontWeight:'800',color:'#647FA3',marginLeft:4},block:{paddingHorizontal:14,marginBottom:14},blockHead:{minHeight:62,flexDirection:'row',alignItems:'center',borderBottomWidth:1,borderBottomColor:C.line},blockTitle:{fontSize:20,fontWeight:'900',color:C.navy,flex:1},row:{minHeight:90,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:1,borderBottomColor:C.line},rowTitle:{fontSize:18,fontWeight:'900',color:C.navy},rowSub:{fontSize:13,color:'#7186A3',fontWeight:'700',marginTop:4},goodPill:{backgroundColor:C.greenBg,color:C.green,paddingHorizontal:14,paddingVertical:8,borderRadius:18,overflow:'hidden',fontWeight:'900',fontSize:15},link:{fontSize:16,fontWeight:'900',color:C.blue},logRow:{height:68,flexDirection:'row',alignItems:'center',gap:10,borderBottomWidth:1,borderBottomColor:C.line},time:{width:48,fontSize:15,color:C.text2,fontWeight:'700'},logName:{width:72,fontSize:16,fontWeight:'900',color:C.text},logAction:{flex:1,fontSize:15,fontWeight:'900',color:C.green},notice:{height:78,borderRadius:22,borderWidth:1,borderColor:'#B9E3F7',backgroundColor:'rgba(229,247,255,.9)',flexDirection:'row',alignItems:'center',paddingHorizontal:20,gap:14},noticeIcon:{fontSize:30},noticeText:{flex:1,fontSize:19,fontWeight:'900',color:C.blue}})
