import React from 'react';
import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { AppItem, LogItem } from '../data';
import { AppIcon, Background, BrandHeader, Card, Chevron, SquareIcon, Toggle } from '../components/UI';
import { BottomNav } from '../components/BottomNav';
import { C } from '../theme';

type HomePermissions={skip:boolean;skipRunning?:boolean;network:boolean;networkRunning?:boolean;bg:boolean;isVivoFamily?:boolean;vendorStartupGuideConfirmed?:boolean};
export default function HomeScreen({master,onMaster,onTab,onPermissions,onRecords,apps,logs,today,permissions}:{master:boolean;onMaster:()=>void;onTab:(t:'home'|'apps'|'settings')=>void;onPermissions:()=>void;onRecords:()=>void;apps:AppItem[];logs:LogItem[];today:{skip:number;network:number};permissions:HomePermissions}){
 const recent=logs.slice(0,3);
 const backgroundStatus=permissions.isVivoFamily&&!permissions.vendorStartupGuideConfirmed?'需开自启动':permissions.isVivoFamily?'已完成检查':permissions.bg?'已允许':'需设置';
 const skipStatus=permissions.skipRunning?'已开启':permissions.skip?'启动中':'需设置';
 const rows=[['≫','blue','自动跳过权限',skipStatus],['◆','green','网络过滤状态',permissions.networkRunning?'运行中':permissions.network?'已授权':'未开启'],['▣','purple','后台运行',backgroundStatus]];
 const total=today.skip+today.network;
 const active=master&&(Boolean(permissions.skipRunning)||Boolean(permissions.networkRunning));
 const statusTitle=active?'净屏已开启':master&&permissions.skip?'等待服务启动':master?'等待授权':'净屏已暂停';
 return <Background><View style={s.root}><ScrollView showsVerticalScrollIndicator={false} contentContainerStyle={s.scroll}><BrandHeader/>
  <Card style={s.status}><LinearGradient colors={active?['#16A9F0','#11D3C0']:['#AFC1D9','#C6D1DF']} style={s.orb}><Text style={s.check}>{active?'✓':master?'!':'–'}</Text></LinearGradient><View style={{flex:1}}><Text style={s.statusTitle}>{statusTitle}</Text></View><Toggle value={master} onChange={onMaster}/></Card>
  <View style={s.stats}><Pressable style={{flex:1}} onPress={onRecords}><Card style={s.stat}><SquareIcon symbol="≫" tone="blue" size={62}/><View><Text style={s.statLabel}>今日自动跳过</Text><View style={s.numRow}><Text style={s.num}>{today.skip}</Text><Text style={s.unit}>次</Text></View></View></Card></Pressable><Pressable style={{flex:1}} onPress={onRecords}><Card style={s.stat}><SquareIcon symbol="◎" tone="green" size={62}/><View><Text style={s.statLabel}>今日网络过滤</Text><View style={s.numRow}><Text style={s.num}>{today.network}</Text><Text style={s.unit}>次</Text></View></View></Card></Pressable></View>
  <Card style={s.block}><View style={s.blockHead}><Text style={s.blockTitle}>◷  权限与服务状态</Text><Pressable onPress={onPermissions}><Chevron/></Pressable></View>
   {rows.map((r:any,i)=><Pressable key={i} onPress={onPermissions} style={s.row}><SquareIcon symbol={r[0]} tone={r[1]} size={52}/><View style={{flex:1}}><Text style={s.rowTitle}>{r[2]}</Text></View><Text style={[s.goodPill,(r[3]==='未开启'||r[3]==='需设置')&&{backgroundColor:'#EDF1F6',color:'#7186A3'}]}>{r[3]}</Text><Chevron/></Pressable>)}
  </Card>
  <Card style={s.block}><View style={s.blockHead}><Text style={s.blockTitle}>◷  最近记录</Text><Pressable onPress={onRecords}><Text style={s.link}>查看全部  ›</Text></Pressable></View>{recent.map((l,i)=>{const a=apps.find(x=>x.id===l.appId);if(!a)return null;return <View key={`${l.appId}-${l.timestamp||i}`} style={s.logRow}><Text style={s.time}>{l.time}</Text><AppIcon source={a.icon} size={42}/><Text style={s.logName}>{a.name}</Text><Text style={[s.logAction,l.type==='fail'&&{color:C.red}]}>●  {l.text}</Text></View>})}</Card>
  <Pressable onPress={onRecords}><View style={s.notice}><Text style={s.noticeIcon}>💡</Text><Text style={s.noticeText}>{total?`已为你减少 ${total} 次广告打扰`:'暂无真实拦截记录'}</Text><Chevron/></View></Pressable>
 </ScrollView><BottomNav active="home" onChange={onTab}/></View></Background>
}
const s=StyleSheet.create({root:{flex:1},scroll:{padding:18,paddingBottom:112},status:{padding:20,flexDirection:'row',alignItems:'center',gap:16,marginBottom:14},orb:{width:94,height:94,borderRadius:47,alignItems:'center',justifyContent:'center'},check:{fontSize:55,color:'#fff',fontWeight:'900'},statusTitle:{fontSize:30,fontWeight:'900',color:C.navy},stats:{flexDirection:'row',gap:12,marginBottom:14},stat:{padding:15,flexDirection:'row',alignItems:'center',gap:12,minHeight:112},statLabel:{fontSize:15,fontWeight:'900',color:C.text},numRow:{flexDirection:'row',alignItems:'baseline'},num:{fontSize:38,fontWeight:'900',color:C.navy},unit:{fontSize:17,fontWeight:'800',color:'#647FA3',marginLeft:4},block:{paddingHorizontal:14,marginBottom:14},blockHead:{minHeight:62,flexDirection:'row',alignItems:'center',borderBottomWidth:1,borderBottomColor:C.line},blockTitle:{fontSize:20,fontWeight:'900',color:C.navy,flex:1},row:{minHeight:78,flexDirection:'row',alignItems:'center',gap:12,borderBottomWidth:1,borderBottomColor:C.line},rowTitle:{fontSize:18,fontWeight:'900',color:C.navy},goodPill:{backgroundColor:C.greenBg,color:C.green,paddingHorizontal:14,paddingVertical:8,borderRadius:18,overflow:'hidden',fontWeight:'900',fontSize:15},link:{fontSize:16,fontWeight:'900',color:C.blue},logRow:{height:68,flexDirection:'row',alignItems:'center',gap:10,borderBottomWidth:1,borderBottomColor:C.line},time:{width:48,fontSize:15,color:C.text2,fontWeight:'700'},logName:{width:72,fontSize:16,fontWeight:'900',color:C.text},logAction:{flex:1,fontSize:15,fontWeight:'900',color:C.green},notice:{height:78,borderRadius:22,borderWidth:1,borderColor:'#B9E3F7',backgroundColor:'rgba(229,247,255,.9)',flexDirection:'row',alignItems:'center',paddingHorizontal:20,gap:14},noticeIcon:{fontSize:30},noticeText:{flex:1,fontSize:19,fontWeight:'900',color:C.blue}})
